# Generated by Django 4.2.20 on 2025-03-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='price',
        ),
    ]
