# Generated by Django 4.2.20 on 2025-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_rename_description_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Comment',
            field=models.TextField(max_length=1000),
        ),
    ]
