# Generated by Django 4.2.20 on 2025-05-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0008_customers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='user',
        ),
    ]
